declare module "react-syntax-highlighter/prism-light"
declare module "react-syntax-highlighter/languages/prism/typescript"
declare module "react-syntax-highlighter/styles/prism"
declare module "react-syntax-highlighter/dist/prism-light"
declare module "react-syntax-highlighter/dist/languages/prism/typescript"
declare module "react-syntax-highlighter/dist/styles/prism"