import * as React from 'react'
import PageContainer from '../components/pageContainer';
import BulmaHero from '../components/hero';
import { FaBalanceScale } from 'react-icons/fa';

let fossaeReport = `

Generated by fossa-cli (https://github.com/fossas/fossa-cli).
This software includes the following software and licenses:

========================================================================
Apache-2.0
========================================================================
The following software have components provided under the terms of this license:

- atob (from https://www.npmjs.com/package/atob)
- localforage (from https://www.npmjs.com/package/localforage)
- react (from https://facebook.github.io/react/)
- react-dom (from https://facebook.github.io/react/)
- react-icons (from https://www.npmjs.com/package/react-icons)
- tslib (from https://www.npmjs.com/package/tslib)

========================================================================
BSD-3-Clause
========================================================================
The following software have components provided under the terms of this license:

- highlight.js (from https://highlightjs.org/)
- prop-types (from https://www.npmjs.com/package/prop-types)
- react (from https://facebook.github.io/react/)
- react-dom (from https://facebook.github.io/react/)
- regenerator-runtime (from https://www.npmjs.com/package/regenerator-runtime)
- source-map (from https://github.com/mozilla/source-map)
- source-map (from https://github.com/mozilla/source-map)
- uuid (from https://github.com/shtylman/node-uuid)

========================================================================
CC-BY-3.0
========================================================================
The following software have components provided under the terms of this license:

- atob (from https://www.npmjs.com/package/atob)
- posix-character-classes (from https://www.npmjs.com/package/posix-character-classes)

========================================================================
CC-BY-SA-3.0
========================================================================
The following software have components provided under the terms of this license:

- react-icons (from https://www.npmjs.com/package/react-icons)

========================================================================
CC0-1.0
========================================================================
The following software have components provided under the terms of this license:

- highlight.js (from https://highlightjs.org/)

========================================================================
GPL-3.0-only
========================================================================
The following software have components provided under the terms of this license:

- es5-ext (from https://github.com/medikoo/es5-ext#readme)

========================================================================
ISC
========================================================================
The following software have components provided under the terms of this license:

- es5-ext (from https://github.com/medikoo/es5-ext#readme)
- graceful-fs (from https://github.com/isaacs/node-graceful-fs#readme)
- inherits (from https://github.com/isaacs/inherits/issues)
- inherits (from https://github.com/isaacs/inherits/issues)

========================================================================
MIT
========================================================================
The following software have components provided under the terms of this license:

- @babel/runtime (from https://www.npmjs.com/package/@babel/runtime)
- ansi-styles (from https://github.com/chalk/ansi-styles)
- arr-diff (from https://github.com/jonschlinkert/arr-diff)
- arr-flatten (from https://www.npmjs.com/package/arr-flatten)
- arr-union (from https://www.npmjs.com/package/arr-union)
- array-unique (from https://www.npmjs.com/package/array-unique)
- assert (from https://github.com/defunctzombie/commonjs-assert)
- assign-symbols (from https://www.npmjs.com/package/assign-symbols)
- atob (from https://www.npmjs.com/package/atob)
- awesome-typescript-loader (from https://www.npmjs.com/package/awesome-typescript-loader)
- base (from https://www.npmjs.com/package/base)
- big.js (from https://github.com/MikeMcl/big.js#readme)
- braces (from https://github.com/jonschlinkert/braces)
- buffer-from (from https://www.npmjs.com/package/buffer-from)
- bulma (from https://www.npmjs.com/package/bulma)
- cache-base (from https://www.npmjs.com/package/cache-base)
- chalk (from https://github.com/chalk/chalk#readme)
- character-entities (from https://www.npmjs.com/package/character-entities)
- character-entities-legacy (from https://www.npmjs.com/package/character-entities-legacy)
- character-reference-invalid (from https://www.npmjs.com/package/character-reference-invalid)
- class-utils (from https://www.npmjs.com/package/class-utils)
- clipboard (from https://www.npmjs.com/package/clipboard)
- collection-visit (from https://www.npmjs.com/package/collection-visit)
- color-convert (from https://github.com/qix-/color-convert#readme)
- color-name (from https://github.com/dfcreative/color-name)
- comma-separated-tokens (from https://www.npmjs.com/package/comma-separated-tokens)
- component-emitter (from https://github.com/component/emitter)
- copy-descriptor (from https://www.npmjs.com/package/copy-descriptor)
- core-util-is (from https://github.com/isaacs/core-util-is#readme)
- d (from https://github.com/medikoo/d#readme)
- debug (from https://github.com/visionmedia/debug)
- decode-uri-component (from https://www.npmjs.com/package/decode-uri-component)
- define-properties (from https://www.npmjs.com/package/define-properties)
- define-property (from https://www.npmjs.com/package/define-property)
- define-property (from https://www.npmjs.com/package/define-property)
- define-property (from https://www.npmjs.com/package/define-property)
- delegate (from https://www.npmjs.com/package/delegate)
- emojis-list (from https://www.npmjs.com/package/emojis-list)
- enhanced-resolve (from http://github.com/webpack/enhanced-resolve)
- errno (from https://github.com/rvagg/node-errno)
- es5-ext (from https://github.com/medikoo/es5-ext#readme)
- es6-iterator (from https://github.com/medikoo/es6-iterator#readme)
- es6-symbol (from https://github.com/medikoo/es6-symbol#readme)
- escape-string-regexp (from https://github.com/sindresorhus/escape-string-regexp)
- expand-brackets (from https://github.com/jonschlinkert/expand-brackets)
- extend-shallow (from https://github.com/jonschlinkert/extend-shallow)
- extend-shallow (from https://github.com/jonschlinkert/extend-shallow)
- extglob (from https://www.npmjs.com/package/extglob)
- fault (from https://www.npmjs.com/package/fault)
- fill-range (from https://github.com/jonschlinkert/fill-range)
- for-in (from https://github.com/jonschlinkert/for-in)
- format (from https://www.npmjs.com/package/format)
- fragment-cache (from https://www.npmjs.com/package/fragment-cache)
- function-bind (from https://www.npmjs.com/package/function-bind)
- get-value (from https://www.npmjs.com/package/get-value)
- good-listener (from https://www.npmjs.com/package/good-listener)
- graceful-fs (from https://github.com/isaacs/node-graceful-fs#readme)
- has-flag (from https://github.com/sindresorhus/has-flag#readme)
- has-symbols (from https://www.npmjs.com/package/has-symbols)
- has-value (from https://github.com/jonschlinkert/has-value)
- has-value (from https://github.com/jonschlinkert/has-value)
- has-values (from https://www.npmjs.com/package/has-values)
- has-values (from https://www.npmjs.com/package/has-values)
- hast-util-parse-selector (from https://www.npmjs.com/package/hast-util-parse-selector)
- hastscript (from https://www.npmjs.com/package/hastscript)
- highlight.js (from https://highlightjs.org/)
- immediate (from https://www.npmjs.com/package/immediate)
- inherits (from https://github.com/isaacs/inherits/issues)
- inherits (from https://github.com/isaacs/inherits/issues)
- is-accessor-descriptor (from https://www.npmjs.com/package/is-accessor-descriptor)
- is-accessor-descriptor (from https://www.npmjs.com/package/is-accessor-descriptor)
- is-alphabetical (from https://www.npmjs.com/package/is-alphabetical)
- is-alphanumerical (from https://www.npmjs.com/package/is-alphanumerical)
- is-buffer (from http://feross.org)
- is-data-descriptor (from https://www.npmjs.com/package/is-data-descriptor)
- is-data-descriptor (from https://www.npmjs.com/package/is-data-descriptor)
- is-decimal (from https://www.npmjs.com/package/is-decimal)
- is-descriptor (from https://www.npmjs.com/package/is-descriptor)
- is-descriptor (from https://www.npmjs.com/package/is-descriptor)
- is-extendable (from https://www.npmjs.com/package/is-extendable)
- is-extendable (from https://www.npmjs.com/package/is-extendable)
- is-hexadecimal (from https://www.npmjs.com/package/is-hexadecimal)
- is-number (from https://github.com/jonschlinkert/is-number)
- is-plain-object (from https://www.npmjs.com/package/is-plain-object)
- is-windows (from https://www.npmjs.com/package/is-windows)
- isarray (from https://github.com/juliangruber/isarray)
- isobject (from https://github.com/jonschlinkert/isobject)
- isobject (from https://github.com/jonschlinkert/isobject)
- js-tokens (from https://github.com/lydell/js-tokens#readme)
- json5 (from http://json5.org/)
- kind-of (from https://github.com/jonschlinkert/kind-of)
- kind-of (from https://github.com/jonschlinkert/kind-of)
- kind-of (from https://github.com/jonschlinkert/kind-of)
- kind-of (from https://github.com/jonschlinkert/kind-of)
- lie (from https://www.npmjs.com/package/lie)
- loader-utils (from https://github.com/webpack/loader-utils#readme)
- localforage (from https://www.npmjs.com/package/localforage)
- lodash (from https://lodash.com/)
- lodash.get (from https://www.npmjs.com/package/lodash.get)
- lodash.set (from https://www.npmjs.com/package/lodash.set)
- log-symbols (from https://www.npmjs.com/package/log-symbols)
- loglevelnext (from https://www.npmjs.com/package/loglevelnext)
- loose-envify (from https://github.com/zertosh/loose-envify)
- lowlight (from https://www.npmjs.com/package/lowlight)
- map-cache (from https://www.npmjs.com/package/map-cache)
- map-visit (from https://www.npmjs.com/package/map-visit)
- memory-fs (from https://github.com/webpack/memory-fs)
- micromatch (from https://github.com/jonschlinkert/micromatch)
- minimist (from https://github.com/substack/minimist)
- mixin-deep (from https://www.npmjs.com/package/mixin-deep)
- mkdirp (from https://github.com/substack/node-mkdirp#readme)
- moment (from http://momentjs.com)
- ms (from https://github.com/guille/ms.js)
- nanomatch (from https://www.npmjs.com/package/nanomatch)
- next-tick (from https://github.com/medikoo/next-tick)
- object-assign (from https://github.com/sindresorhus/object-assign#readme)
- object-copy (from https://www.npmjs.com/package/object-copy)
- object-keys (from https://github.com/ljharb/object-keys#readme)
- object-visit (from https://www.npmjs.com/package/object-visit)
- object.assign (from https://www.npmjs.com/package/object.assign)
- object.pick (from https://github.com/jonschlinkert/object.pick)
- parse-entities (from https://www.npmjs.com/package/parse-entities)
- pascalcase (from https://www.npmjs.com/package/pascalcase)
- posix-character-classes (from https://www.npmjs.com/package/posix-character-classes)
- prismjs (from https://www.npmjs.com/package/prismjs)
- process-nextick-args (from https://github.com/calvinmetcalf/process-nextick-args)
- prop-types (from https://www.npmjs.com/package/prop-types)
- property-information (from https://www.npmjs.com/package/property-information)
- prr (from https://github.com/rvagg/prr)
- react (from https://facebook.github.io/react/)
- react-dom (from https://facebook.github.io/react/)
- react-icons (from https://www.npmjs.com/package/react-icons)
- react-syntax-highlighter (from https://www.npmjs.com/package/react-syntax-highlighter)
- readable-stream (from https://github.com/nodejs/readable-stream#readme)
- refractor (from https://www.npmjs.com/package/refractor)
- regenerator-runtime (from https://www.npmjs.com/package/regenerator-runtime)
- regex-not (from https://www.npmjs.com/package/regex-not)
- repeat-element (from https://github.com/jonschlinkert/repeat-element)
- repeat-string (from https://github.com/jonschlinkert/repeat-string)
- resolve-url (from https://www.npmjs.com/package/resolve-url)
- ret (from https://www.npmjs.com/package/ret)
- safe-buffer (from https://www.npmjs.com/package/safe-buffer)
- safe-regex (from https://www.npmjs.com/package/safe-regex)
- scheduler (from https://www.npmjs.com/package/scheduler)
- select (from https://www.npmjs.com/package/select)
- set-value (from https://www.npmjs.com/package/set-value)
- set-value (from https://www.npmjs.com/package/set-value)
- snapdragon (from https://www.npmjs.com/package/snapdragon)
- snapdragon-node (from https://www.npmjs.com/package/snapdragon-node)
- snapdragon-util (from https://www.npmjs.com/package/snapdragon-util)
- source-map-resolve (from https://www.npmjs.com/package/source-map-resolve)
- source-map-support (from https://github.com/evanw/node-source-map-support#readme)
- source-map-url (from https://www.npmjs.com/package/source-map-url)
- space-separated-tokens (from https://www.npmjs.com/package/space-separated-tokens)
- split-string (from https://www.npmjs.com/package/split-string)
- static-extend (from https://www.npmjs.com/package/static-extend)
- string_decoder (from https://github.com/rvagg/string_decoder)
- supports-color (from https://github.com/chalk/supports-color)
- tapable (from https://github.com/webpack/tapable)
- tiny-emitter (from https://www.npmjs.com/package/tiny-emitter)
- to-object-path (from https://www.npmjs.com/package/to-object-path)
- to-regex (from https://www.npmjs.com/package/to-regex)
- to-regex-range (from https://www.npmjs.com/package/to-regex-range)
- trim (from https://www.npmjs.com/package/trim)
- union-value (from https://www.npmjs.com/package/union-value)
- unset-value (from https://www.npmjs.com/package/unset-value)
- urix (from https://www.npmjs.com/package/urix)
- use (from https://www.npmjs.com/package/use)
- util (from https://github.com/defunctzombie/node-util)
- util-deprecate (from https://github.com/TooTallNate/util-deprecate)
- uuid (from https://github.com/shtylman/node-uuid)
- webpack-log (from https://www.npmjs.com/package/webpack-log)
- xtend (from https://github.com/Raynos/xtend)

========================================================================
Public-Domain
========================================================================
The following software have components provided under the terms of this license:

- highlight.js (from https://highlightjs.org/)`
fossaeReport = fossaeReport.replace(/\n/g, "<br />")
class PageLicenses extends React.Component<any, any> {
  public render() {
    return (
      <PageContainer {...this.props}>
        <BulmaHero
          className="is-light"
          title="Open source licenses"
          iconConfig={FaBalanceScale}
        >
        </BulmaHero>
        <div className="content" style={{marginRight: "1rem", marginLeft: "1rem"}} dangerouslySetInnerHTML={{ __html: fossaeReport }} />
      </PageContainer>
    )
  }
}

export default PageLicenses
