import React from 'react'
import PageContainer from '../components/pageContainer';
import BulmaHero from '../components/hero';
import { FaBalanceScale } from 'react-icons/fa';

let licenseReport = `abab licensed under BSD-3-Clause. Repository: git+https://github.com/jsdom/abab.git
abbrev licensed under ISC. Repository: http://github.com/isaacs/abbrev-js
accepts licensed under MIT. Repository: jshttp/accepts
acorn licensed under MIT. Repository: https://github.com/acornjs/acorn.git
acorn-globals licensed under MIT. Repository: https://github.com/ForbesLindesay/acorn-globals.git
acorn-walk licensed under MIT. Repository: https://github.com/acornjs/acorn.git
after licensed under MIT. Repository: git://github.com/Raynos/after.git
ajv licensed under MIT. Repository: https://github.com/epoberezkin/ajv.git
ajv-errors licensed under MIT. Repository: git+https://github.com/epoberezkin/ajv-errors.git
ajv-keywords licensed under MIT. Repository: git+https://github.com/epoberezkin/ajv-keywords.git
amdefine licensed under BSD-3-Clause OR MIT. Repository: https://github.com/jrburke/amdefine.git
ansi-colors licensed under MIT. Repository: doowb/ansi-colors
ansi-escapes licensed under MIT. Repository: sindresorhus/ansi-escapes
ansi-html licensed under Apache-2.0. Repository: git://github.com/Tjatse/ansi-html.git
ansi-regex licensed under MIT. Repository: chalk/ansi-regex
ansi-styles licensed under MIT. Repository: chalk/ansi-styles
anymatch licensed under ISC. Repository: https://github.com/micromatch/anymatch
aproba licensed under ISC. Repository: https://github.com/iarna/aproba
are-we-there-yet licensed under ISC. Repository: https://github.com/iarna/are-we-there-yet.git
arg licensed under MIT. Repository: zeit/arg
argparse licensed under MIT. Repository: nodeca/argparse
arr-diff licensed under MIT. Repository: jonschlinkert/arr-diff
arr-flatten licensed under MIT. Repository: jonschlinkert/arr-flatten
arr-union licensed under MIT. Repository: jonschlinkert/arr-union
array-equal licensed under MIT. Repository: component/array-equal
array-find-index licensed under MIT. Repository: sindresorhus/array-find-index
array-flatten licensed under MIT. Repository: git://github.com/blakeembrey/array-flatten.git
array-union licensed under MIT. Repository: sindresorhus/array-union
array-uniq licensed under MIT. Repository: sindresorhus/array-uniq
array-unique licensed under MIT. Repository: jonschlinkert/array-unique
arraybuffer.slice licensed under MIT. Repository: git@github.com:rase-/arraybuffer.slice.git
asn1 licensed under MIT. Repository: git://github.com/joyent/node-asn1.git
asn1.js licensed under MIT. Repository: git@github.com:indutny/asn1.js
assert licensed under MIT. Repository: git://github.com/browserify/commonjs-assert.git
assert-plus licensed under MIT. Repository: https://github.com/mcavage/node-assert-plus.git
assign-symbols licensed under MIT. Repository: jonschlinkert/assign-symbols
astral-regex licensed under MIT. Repository: kevva/astral-regex
async licensed under MIT. Repository: https://github.com/caolan/async.git
async-each licensed under MIT. Repository: git://github.com/paulmillr/async-each.git
async-limiter licensed under MIT. Repository: https://github.com/strml/async-limiter.git
asynckit licensed under MIT. Repository: git+https://github.com/alexindigo/asynckit.git
atob licensed under (MIT OR Apache-2.0). Repository: git://git.coolaj86.com/coolaj86/atob.js.git
awesome-typescript-loader licensed under MIT. Repository: https://github.com/s-panferov/awesome-typescript-loader.git
aws-sign2 licensed under Apache-2.0. Repository: https://github.com/mikeal/aws-sign
aws4 licensed under MIT. Repository: https://github.com/mhart/aws4.git
babel-jest licensed under MIT. Repository: https://github.com/facebook/jest.git
babel-plugin-istanbul licensed under BSD-3-Clause. Repository: git+https://github.com/istanbuljs/babel-plugin-istanbul.git
babel-plugin-jest-hoist licensed under MIT. Repository: https://github.com/facebook/jest.git
babel-preset-jest licensed under MIT. Repository: https://github.com/facebook/jest.git
babel-runtime licensed under MIT. Repository: https://github.com/babel/babel/tree/master/packages/babel-runtime
backo2 licensed under MIT. Repository: mokesmokes/backo
balanced-match licensed under MIT. Repository: git://github.com/juliangruber/balanced-match.git
base licensed under MIT. Repository: node-base/base
base64-js licensed under MIT. Repository: git://github.com/beatgammit/base64-js.git
base64id licensed under MIT. Repository: https://github.com/faeldt/base64id.git
batch licensed under MIT. Repository: https://github.com/visionmedia/batch.git
bcrypt-pbkdf licensed under BSD-3-Clause. Repository: git://github.com/joyent/node-bcrypt-pbkdf.git
bcryptjs licensed under MIT. Repository: https://github.com/dcodeIO/bcrypt.js.git
big.js licensed under MIT. Repository: https://github.com/MikeMcl/big.js.git
binary-extensions licensed under MIT. Repository: sindresorhus/binary-extensions
bl licensed under MIT. Repository: https://github.com/rvagg/bl.git
blob licensed under MIT. Repository: git://github.com/webmodules/blob.git
block-stream licensed under ISC. Repository: git://github.com/isaacs/block-stream.git
bluebird licensed under MIT. Repository: git://github.com/petkaantonov/bluebird.git
bn.js licensed under MIT. Repository: git@github.com:indutny/bn.js
body-parser licensed under MIT. Repository: expressjs/body-parser
bonjour licensed under MIT. Repository: https://github.com/watson/bonjour.git
brace-expansion licensed under MIT. Repository: git://github.com/juliangruber/brace-expansion.git
braces licensed under MIT. Repository: micromatch/braces
brorand licensed under MIT. Repository: git@github.com:indutny/brorand
browser-process-hrtime licensed under BSD-2-Clause. Repository: git://github.com/kumavis/browser-process-hrtime.git
browser-resolve licensed under MIT. Repository: git://github.com/shtylman/node-browser-resolve.git
browserify-aes licensed under MIT. Repository: git://github.com/crypto-browserify/browserify-aes.git
browserify-cipher licensed under MIT. Repository: git@github.com:crypto-browserify/browserify-cipher.git
browserify-des licensed under MIT. Repository: git+https://github.com/crypto-browserify/browserify-des.git
browserify-rsa licensed under MIT. Repository: git@github.com:crypto-browserify/browserify-rsa.git
browserify-sign licensed under ISC. Repository: https://github.com/crypto-browserify/browserify-sign.git
browserify-zlib licensed under MIT. Repository: git+https://github.com/devongovett/browserify-zlib.git
bs-logger licensed under MIT. Repository: git+https://github.com/huafu/bs-logger.git
bser licensed under Apache-2.0. Repository: https://github.com/facebook/watchman
bson licensed under Apache-2.0. Repository: mongodb/js-bson
buffer licensed under MIT. Repository: git://github.com/feross/buffer.git
buffer-equal-constant-time licensed under BSD-3-Clause. Repository: git@github.com:goinstant/buffer-equal-constant-time.git
buffer-from licensed under MIT. Repository: LinusU/buffer-from
buffer-indexof licensed under MIT. Repository: git://github.com/soldair/node-buffer-indexof.git
buffer-xor licensed under MIT. Repository: https://github.com/crypto-browserify/buffer-xor.git
builtin-status-codes licensed under MIT. Repository: bendrucker/builtin-status-codes
bulma licensed under MIT. Repository: git+https://github.com/jgthms/bulma.git
bytes licensed under MIT. Repository: visionmedia/bytes.js
cacache licensed under ISC. Repository: https://github.com/npm/cacache
cache-base licensed under MIT. Repository: jonschlinkert/cache-base
callsites licensed under MIT. Repository: sindresorhus/callsites
camelcase licensed under MIT. Repository: sindresorhus/camelcase
camelcase-keys licensed under MIT. Repository: sindresorhus/camelcase-keys
capture-exit licensed under ISC. Repository: git+https://github.com/stefanpenner/capture-exit.git
caseless licensed under Apache-2.0. Repository: https://github.com/mikeal/caseless
chalk licensed under MIT. Repository: chalk/chalk
character-entities licensed under MIT. Repository: wooorm/character-entities
character-entities-legacy licensed under MIT. Repository: wooorm/character-entities-legacy
character-reference-invalid licensed under MIT. Repository: wooorm/character-reference-invalid
chokidar licensed under MIT. Repository: https://github.com/paulmillr/chokidar.git
chownr licensed under ISC. Repository: git://github.com/isaacs/chownr.git
chrome-trace-event licensed under MIT. Repository: github.com:samccone/chrome-trace-event
ci-info licensed under MIT. Repository: https://github.com/watson/ci-info.git
cipher-base licensed under MIT. Repository: git+https://github.com/crypto-browserify/cipher-base.git
class-utils licensed under MIT. Repository: jonschlinkert/class-utils
clipboard licensed under MIT. Repository: zenorocha/clipboard.js
cliui licensed under ISC. Repository: http://github.com/yargs/cliui.git
clone-deep licensed under MIT. Repository: jonschlinkert/clone-deep
co licensed under MIT. Repository: tj/co
code-point-at licensed under MIT. Repository: sindresorhus/code-point-at
collect-v8-coverage licensed under MIT. Repository: 
collection-visit licensed under MIT. Repository: jonschlinkert/collection-visit
color-convert licensed under MIT. Repository: Qix-/color-convert
color-name licensed under MIT. Repository: git@github.com:colorjs/color-name.git
combined-stream licensed under MIT. Repository: git://github.com/felixge/node-combined-stream.git
comma-separated-tokens licensed under MIT. Repository: wooorm/comma-separated-tokens
commander licensed under MIT. Repository: https://github.com/tj/commander.js.git
commondir licensed under MIT. Repository: http://github.com/substack/node-commondir.git
component-emitter licensed under MIT. Repository: https://github.com/component/emitter.git
compressible licensed under MIT. Repository: jshttp/compressible
compression licensed under MIT. Repository: expressjs/compression
concat-map licensed under MIT. Repository: git://github.com/substack/node-concat-map.git
concat-stream licensed under MIT. Repository: http://github.com/maxogden/concat-stream.git
connect-history-api-fallback licensed under MIT. Repository: http://github.com/bripkens/connect-history-api-fallback.git
console-control-strings licensed under ISC. Repository: https://github.com/iarna/console-control-strings
constants-browserify licensed under MIT. Repository: git://github.com/juliangruber/constants-browserify.git
content-disposition licensed under MIT. Repository: jshttp/content-disposition
content-type licensed under MIT. Repository: jshttp/content-type
convert-source-map licensed under MIT. Repository: git://github.com/thlorenz/convert-source-map.git
cookie licensed under MIT. Repository: jshttp/cookie
cookie-signature licensed under MIT. Repository: https://github.com/visionmedia/node-cookie-signature.git
copy-concurrently licensed under ISC. Repository: git+https://github.com/npm/copy-concurrently.git
copy-descriptor licensed under MIT. Repository: jonschlinkert/copy-descriptor
copy-webpack-plugin licensed under MIT. Repository: webpack-contrib/copy-webpack-plugin
core-js licensed under MIT. Repository: https://github.com/zloirock/core-js.git
core-util-is licensed under MIT. Repository: git://github.com/isaacs/core-util-is
create-ecdh licensed under MIT. Repository: https://github.com/crypto-browserify/createECDH.git
create-hash licensed under MIT. Repository: git@github.com:crypto-browserify/createHash.git
create-hmac licensed under MIT. Repository: https://github.com/crypto-browserify/createHmac.git
cross-spawn licensed under MIT. Repository: git@github.com:moxystudio/node-cross-spawn.git
crypto-browserify licensed under MIT. Repository: git://github.com/crypto-browserify/crypto-browserify.git
css-loader licensed under MIT. Repository: webpack-contrib/css-loader
cssesc licensed under MIT. Repository: https://github.com/mathiasbynens/cssesc.git
cssom licensed under MIT. Repository: NV/CSSOM
cssstyle licensed under MIT. Repository: jsdom/cssstyle
csstype licensed under MIT. Repository: https://github.com/frenic/csstype
currently-unhandled licensed under MIT. Repository: jamestalmage/currently-unhandled
cyclist licensed under MIT. Repository: git://github.com/mafintosh/cyclist
d licensed under ISC. Repository: git://github.com/medikoo/d.git
d3-array licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-array.git
d3-collection licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-collection.git
d3-color licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-color.git
d3-ease licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-ease.git
d3-format licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-format.git
d3-interpolate licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-interpolate.git
d3-path licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-path.git
d3-scale licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-scale.git
d3-shape licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-shape.git
d3-time licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-time.git
d3-time-format licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-time-format.git
d3-timer licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-timer.git
d3-voronoi licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-voronoi.git
dashdash licensed under MIT. Repository: git://github.com/trentm/node-dashdash.git
data-urls licensed under MIT. Repository: jsdom/data-urls
debug licensed under MIT. Repository: git://github.com/visionmedia/debug.git
decamelize licensed under MIT. Repository: sindresorhus/decamelize
decode-uri-component licensed under MIT. Repository: SamVerschueren/decode-uri-component
deep-equal licensed under MIT. Repository: http://github.com/substack/node-deep-equal.git
deepmerge licensed under MIT. Repository: git://github.com/TehShrike/deepmerge.git
default-gateway licensed under BSD-2-Clause. Repository: silverwind/default-gateway
define-properties licensed under MIT. Repository: git://github.com/ljharb/define-properties.git
define-property licensed under MIT. Repository: jonschlinkert/define-property
del licensed under MIT. Repository: sindresorhus/del
delaunator licensed under ISC. Repository: https://github.com/mapbox/delaunator.git
delaunay-find licensed under ISC. Repository: https://github.com/FormidableLabs/delaunay-find
delayed-stream licensed under MIT. Repository: git://github.com/felixge/node-delayed-stream.git
delegate licensed under MIT. Repository: zenorocha/delegate
delegates licensed under MIT. Repository: visionmedia/node-delegates
denque licensed under Apache-2.0. Repository: git+https://github.com/invertase/denque.git
depd licensed under MIT. Repository: dougwilson/nodejs-depd
des.js licensed under MIT. Repository: git+ssh://git@github.com/indutny/des.js.git
destroy licensed under MIT. Repository: stream-utils/destroy
detect-file licensed under MIT. Repository: doowb/detect-file
detect-newline licensed under MIT. Repository: sindresorhus/detect-newline
detect-node licensed under ISC. Repository: https://github.com/iliakan/detect-node
diff licensed under BSD-3-Clause. Repository: git://github.com/kpdecker/jsdiff.git
diff-sequences licensed under MIT. Repository: https://github.com/facebook/jest.git
diffie-hellman licensed under MIT. Repository: https://github.com/crypto-browserify/diffie-hellman.git
dir-glob licensed under MIT. Repository: kevva/dir-glob
dns-equal licensed under MIT. Repository: git+https://github.com/watson/dns-equal.git
dns-packet licensed under MIT. Repository: https://github.com/mafintosh/dns-packet
dns-txt licensed under MIT. Repository: https://github.com/watson/dns-txt.git
domain-browser licensed under MIT. Repository: https://github.com/bevry/domain-browser.git
domexception licensed under MIT. Repository: jsdom/domexception
duplexify licensed under MIT. Repository: git://github.com/mafintosh/duplexify
ecc-jsbn licensed under MIT. Repository: https://github.com/quartzjer/ecc-jsbn.git
ecdsa-sig-formatter licensed under Apache-2.0. Repository: git+ssh://git@github.com/Brightspace/node-ecdsa-sig-formatter.git
ee-first licensed under MIT. Repository: jonathanong/ee-first
elliptic licensed under MIT. Repository: git@github.com:indutny/elliptic
emoji-regex licensed under MIT. Repository: https://github.com/mathiasbynens/emoji-regex.git
emojis-list licensed under MIT. Repository: git+https://github.com/kikobeats/emojis-list.git
encodeurl licensed under MIT. Repository: pillarjs/encodeurl
end-of-stream licensed under MIT. Repository: git://github.com/mafintosh/end-of-stream.git
engine.io licensed under MIT. Repository: git@github.com:socketio/engine.io.git
engine.io-client licensed under MIT. Repository: https://github.com/socketio/engine.io-client.git
engine.io-parser licensed under MIT. Repository: git@github.com:socketio/engine.io-parser.git
errno licensed under MIT. Repository: https://github.com/rvagg/node-errno.git
error-ex licensed under MIT. Repository: qix-/node-error-ex
es-abstract licensed under MIT. Repository: git://github.com/ljharb/es-abstract.git
es-to-primitive licensed under MIT. Repository: git://github.com/ljharb/es-to-primitive.git
es5-ext licensed under ISC. Repository: medikoo/es5-ext
es6-iterator licensed under MIT. Repository: git://github.com/medikoo/es6-iterator.git
es6-symbol licensed under ISC. Repository: git://github.com/medikoo/es6-symbol.git
escape-html licensed under MIT. Repository: component/escape-html
escape-string-regexp licensed under MIT. Repository: sindresorhus/escape-string-regexp
escodegen licensed under BSD-2-Clause. Repository: http://github.com/estools/escodegen.git
eslint-scope licensed under BSD-2-Clause. Repository: eslint/eslint-scope
esprima licensed under BSD-2-Clause. Repository: https://github.com/jquery/esprima.git
esrecurse licensed under BSD-2-Clause. Repository: https://github.com/estools/esrecurse.git
estraverse licensed under BSD-2-Clause. Repository: http://github.com/estools/estraverse.git
esutils licensed under BSD-2-Clause. Repository: http://github.com/estools/esutils.git
etag licensed under MIT. Repository: jshttp/etag
eventemitter3 licensed under MIT. Repository: git://github.com/primus/eventemitter3.git
events licensed under MIT. Repository: git://github.com/Gozala/events.git
eventsource licensed under MIT. Repository: git://github.com/EventSource/eventsource.git
evp_bytestokey licensed under MIT. Repository: https://github.com/crypto-browserify/EVP_BytesToKey.git
exec-sh licensed under MIT. Repository: git@github.com:tsertkov/exec-sh.git
execa licensed under MIT. Repository: sindresorhus/execa
expand-brackets licensed under MIT. Repository: jonschlinkert/expand-brackets
expand-tilde licensed under MIT. Repository: jonschlinkert/expand-tilde
expect licensed under MIT. Repository: https://github.com/facebook/jest.git
express licensed under MIT. Repository: expressjs/express
ext licensed under ISC. Repository: https://github.com/medikoo/es5-ext/tree/ext
extend licensed under MIT. Repository: https://github.com/justmoon/node-extend.git
extend-shallow licensed under MIT. Repository: jonschlinkert/extend-shallow
extglob licensed under MIT. Repository: micromatch/extglob
extsprintf licensed under MIT. Repository: git://github.com/davepacheco/node-extsprintf.git
fast-deep-equal licensed under MIT. Repository: git+https://github.com/epoberezkin/fast-deep-equal.git
fast-json-patch licensed under MIT. Repository: git://github.com/Starcounter-Jack/JSON-Patch.git
fast-json-stable-stringify licensed under MIT. Repository: git://github.com/epoberezkin/fast-json-stable-stringify.git
fast-levenshtein licensed under MIT. Repository: https://github.com/hiddentao/fast-levenshtein.git
fault licensed under MIT. Repository: wooorm/fault
faye-websocket licensed under MIT. Repository: git://github.com/faye/faye-websocket-node.git
fb-watchman licensed under Apache-2.0. Repository: git@github.com:facebook/watchman.git
feathers-memory licensed under MIT. Repository: git://github.com/feathersjs-ecosystem/feathers-memory.git
feathers-mongodb licensed under MIT. Repository: git://github.com/feathersjs-ecosystem/feathers-mongodb.git
figgy-pudding licensed under ISC. Repository: https://github.com/npm/figgy-pudding
file-loader licensed under MIT. Repository: webpack-contrib/file-loader
fill-range licensed under MIT. Repository: jonschlinkert/fill-range
finalhandler licensed under MIT. Repository: pillarjs/finalhandler
find-cache-dir licensed under MIT. Repository: avajs/find-cache-dir
find-up licensed under MIT. Repository: sindresorhus/find-up
findup-sync licensed under MIT. Repository: gulpjs/findup-sync
flush-write-stream licensed under MIT. Repository: https://github.com/mafintosh/flush-write-stream.git
follow-redirects licensed under MIT. Repository: git@github.com:follow-redirects/follow-redirects.git
for-in licensed under MIT. Repository: jonschlinkert/for-in
forever-agent licensed under Apache-2.0. Repository: https://github.com/mikeal/forever-agent
form-data licensed under MIT. Repository: git://github.com/form-data/form-data.git
forwarded licensed under MIT. Repository: jshttp/forwarded
fragment-cache licensed under MIT. Repository: jonschlinkert/fragment-cache
fresh licensed under MIT. Repository: jshttp/fresh
from2 licensed under MIT. Repository: git://github.com/hughsk/from2
fs-write-stream-atomic licensed under ISC. Repository: https://github.com/npm/fs-write-stream-atomic
fs.realpath licensed under ISC. Repository: git+https://github.com/isaacs/fs.realpath.git
fstream licensed under ISC. Repository: https://github.com/npm/fstream.git
function-bind licensed under MIT. Repository: git://github.com/Raynos/function-bind.git
gauge licensed under ISC. Repository: https://github.com/iarna/gauge
gaze licensed under MIT. Repository: https://github.com/shama/gaze.git
gensync licensed under MIT. Repository: 
get-caller-file licensed under ISC. Repository: git+https://github.com/stefanpenner/get-caller-file.git
get-stdin licensed under MIT. Repository: sindresorhus/get-stdin
get-stream licensed under MIT. Repository: sindresorhus/get-stream
get-value licensed under MIT. Repository: jonschlinkert/get-value
getpass licensed under MIT. Repository: https://github.com/arekinath/node-getpass.git
glob licensed under ISC. Repository: git://github.com/isaacs/node-glob.git
glob-parent licensed under ISC. Repository: https://github.com/es128/glob-parent
global-modules licensed under MIT. Repository: jonschlinkert/global-modules
global-prefix licensed under MIT. Repository: jonschlinkert/global-prefix
globals licensed under MIT. Repository: sindresorhus/globals
globby licensed under MIT. Repository: sindresorhus/globby
globule licensed under MIT. Repository: git://github.com/cowboy/node-globule.git
good-listener licensed under MIT. Repository: zenorocha/good-listener
graceful-fs licensed under ISC. Repository: https://github.com/isaacs/node-graceful-fs
growly licensed under MIT. Repository: http://github.com/theabraham/growly
handle-thing licensed under MIT. Repository: git+ssh://git@github.com/indutny/handle-thing.git
har-schema licensed under ISC. Repository: https://github.com/ahmadnassri/har-schema.git
har-validator licensed under MIT. Repository: https://github.com/ahmadnassri/node-har-validator.git
has licensed under MIT. Repository: git://github.com/tarruda/has.git
has-ansi licensed under MIT. Repository: sindresorhus/has-ansi
has-binary2 licensed under MIT. Repository: 
has-cors licensed under MIT. Repository: git://github.com/component/has-cors.git
has-flag licensed under MIT. Repository: sindresorhus/has-flag
has-symbols licensed under MIT. Repository: git://github.com/ljharb/has-symbols.git
has-unicode licensed under ISC. Repository: https://github.com/iarna/has-unicode
has-value licensed under MIT. Repository: jonschlinkert/has-value
has-values licensed under MIT. Repository: jonschlinkert/has-values
hash-base licensed under MIT. Repository: https://github.com/crypto-browserify/hash-base.git
hash.js licensed under MIT. Repository: git@github.com:indutny/hash.js
hast-util-parse-selector licensed under MIT. Repository: syntax-tree/hast-util-parse-selector
hastscript licensed under MIT. Repository: syntax-tree/hastscript
highlight.js licensed under BSD-3-Clause. Repository: git://github.com/highlightjs/highlight.js.git
hmac-drbg licensed under MIT. Repository: git+ssh://git@github.com/indutny/hmac-drbg.git
homedir-polyfill licensed under MIT. Repository: doowb/homedir-polyfill
hosted-git-info licensed under ISC. Repository: git+https://github.com/npm/hosted-git-info.git
hpack.js licensed under MIT. Repository: git+ssh://git@github.com/indutny/hpack.js.git
html-encoding-sniffer licensed under MIT. Repository: jsdom/html-encoding-sniffer
html-entities licensed under MIT. Repository: https://github.com/mdevils/node-html-entities.git
html-escaper licensed under MIT. Repository: https://github.com/WebReflection/html-escaper.git
http-deceiver licensed under MIT. Repository: git+ssh://git@github.com/indutny/http-deceiver.git
http-errors licensed under MIT. Repository: jshttp/http-errors
http-parser-js licensed under MIT. Repository: git://github.com/creationix/http-parser-js.git
http-proxy licensed under MIT. Repository: https://github.com/http-party/node-http-proxy.git
http-proxy-middleware licensed under MIT. Repository: https://github.com/chimurai/http-proxy-middleware.git
http-signature licensed under MIT. Repository: git://github.com/joyent/node-http-signature.git
https-browserify licensed under MIT. Repository: git://github.com/substack/https-browserify.git
human-signals licensed under Apache-2.0. Repository: ehmicky/human-signals
iconv-lite licensed under MIT. Repository: git://github.com/ashtuchkin/iconv-lite.git
icss-utils licensed under ISC. Repository: git+https://github.com/css-modules/icss-utils.git
ieee754 licensed under BSD-3-Clause. Repository: git://github.com/feross/ieee754.git
iferr licensed under MIT. Repository: https://github.com/shesek/iferr
ignore licensed under MIT. Repository: git@github.com:kaelzhang/node-ignore.git
immediate licensed under MIT. Repository: git://github.com/calvinmetcalf/immediate.git
import-local licensed under MIT. Repository: sindresorhus/import-local
imurmurhash licensed under MIT. Repository: https://github.com/jensyt/imurmurhash-js
in-publish licensed under ISC. Repository: https://github.com/iarna/in-publish
indent-string licensed under MIT. Repository: sindresorhus/indent-string
indexes-of licensed under MIT. Repository: git://github.com/dominictarr/indexes-of.git
infer-owner licensed under ISC. Repository: https://github.com/npm/infer-owner
inflight licensed under ISC. Repository: https://github.com/npm/inflight.git
inherits licensed under ISC. Repository: git://github.com/isaacs/inherits
ini licensed under ISC. Repository: git://github.com/isaacs/ini.git
internal-ip licensed under MIT. Repository: sindresorhus/internal-ip
interpret licensed under MIT. Repository: gulpjs/interpret
invert-kv licensed under MIT. Repository: sindresorhus/invert-kv
ip licensed under MIT. Repository: http://github.com/indutny/node-ip.git
ip-regex licensed under MIT. Repository: sindresorhus/ip-regex
ipaddr.js licensed under MIT. Repository: git://github.com/whitequark/ipaddr.js
is-absolute-url licensed under MIT. Repository: sindresorhus/is-absolute-url
is-accessor-descriptor licensed under MIT. Repository: jonschlinkert/is-accessor-descriptor
is-alphabetical licensed under MIT. Repository: wooorm/is-alphabetical
is-alphanumerical licensed under MIT. Repository: wooorm/is-alphanumerical
is-arguments licensed under MIT. Repository: git://github.com/ljharb/is-arguments.git
is-arrayish licensed under MIT. Repository: https://github.com/qix-/node-is-arrayish.git
is-binary-path licensed under MIT. Repository: sindresorhus/is-binary-path
is-buffer licensed under MIT. Repository: git://github.com/feross/is-buffer.git
is-callable licensed under MIT. Repository: git://github.com/ljharb/is-callable.git
is-ci licensed under MIT. Repository: https://github.com/watson/is-ci.git
is-data-descriptor licensed under MIT. Repository: jonschlinkert/is-data-descriptor
is-date-object licensed under MIT. Repository: git://github.com/ljharb/is-date-object.git
is-decimal licensed under MIT. Repository: wooorm/is-decimal
is-descriptor licensed under MIT. Repository: jonschlinkert/is-descriptor
is-extendable licensed under MIT. Repository: jonschlinkert/is-extendable
is-extglob licensed under MIT. Repository: jonschlinkert/is-extglob
is-finite licensed under MIT. Repository: sindresorhus/is-finite
is-fullwidth-code-point licensed under MIT. Repository: sindresorhus/is-fullwidth-code-point
is-generator-fn licensed under MIT. Repository: sindresorhus/is-generator-fn
is-glob licensed under MIT. Repository: micromatch/is-glob
is-hexadecimal licensed under MIT. Repository: wooorm/is-hexadecimal
is-number licensed under MIT. Repository: jonschlinkert/is-number
is-path-cwd licensed under MIT. Repository: sindresorhus/is-path-cwd
is-path-in-cwd licensed under MIT. Repository: sindresorhus/is-path-in-cwd
is-path-inside licensed under MIT. Repository: sindresorhus/is-path-inside
is-plain-obj licensed under MIT. Repository: sindresorhus/is-plain-obj
is-plain-object licensed under MIT. Repository: jonschlinkert/is-plain-object
is-regex licensed under MIT. Repository: git://github.com/ljharb/is-regex.git
is-stream licensed under MIT. Repository: sindresorhus/is-stream
is-symbol licensed under MIT. Repository: git://github.com/inspect-js/is-symbol.git
is-typedarray licensed under MIT. Repository: git://github.com/hughsk/is-typedarray.git
is-utf8 licensed under MIT. Repository: https://github.com/wayfind/is-utf8.git
is-windows licensed under MIT. Repository: jonschlinkert/is-windows
is-wsl licensed under MIT. Repository: sindresorhus/is-wsl
isarray licensed under MIT. Repository: git://github.com/juliangruber/isarray.git
isexe licensed under ISC. Repository: git+https://github.com/isaacs/isexe.git
isobject licensed under MIT. Repository: jonschlinkert/isobject
isstream licensed under MIT. Repository: https://github.com/rvagg/isstream.git
istanbul-lib-coverage licensed under BSD-3-Clause. Repository: git+ssh://git@github.com/istanbuljs/istanbuljs.git
istanbul-lib-instrument licensed under BSD-3-Clause. Repository: git+ssh://git@github.com/istanbuljs/istanbuljs.git
istanbul-lib-report licensed under BSD-3-Clause. Repository: git+ssh://git@github.com/istanbuljs/istanbuljs.git
istanbul-lib-source-maps licensed under BSD-3-Clause. Repository: git+ssh://git@github.com/istanbuljs/istanbuljs.git
istanbul-reports licensed under BSD-3-Clause. Repository: git+ssh://git@github.com/istanbuljs/istanbuljs.git
jest licensed under MIT. Repository: https://github.com/facebook/jest
jest-changed-files licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-cli licensed under MIT. Repository: https://github.com/facebook/jest
jest-config licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-diff licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-docblock licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-each licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-environment-jsdom licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-environment-node licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-get-type licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-haste-map licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-jasmine2 licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-leak-detector licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-matcher-utils licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-message-util licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-mock licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-pnp-resolver licensed under MIT. Repository: https://github.com/arcanis/jest-pnp-resolver.git
jest-regex-util licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-resolve licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-resolve-dependencies licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-runner licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-runtime licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-serializer licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-snapshot licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-util licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-validate licensed under MIT. Repository: https://github.com/facebook/jest.git
jest-watcher licensed under MIT. Repository: https://github.com/facebook/jest
jest-worker licensed under MIT. Repository: https://github.com/facebook/jest.git
js-base64 licensed under BSD-3-Clause. Repository: git://github.com/dankogai/js-base64.git
js-tokens licensed under MIT. Repository: lydell/js-tokens
js-yaml licensed under MIT. Repository: nodeca/js-yaml
jsbn licensed under MIT. Repository: https://github.com/andyperlitch/jsbn.git
jsdom licensed under MIT. Repository: jsdom/jsdom
jsesc licensed under MIT. Repository: https://github.com/mathiasbynens/jsesc.git
json-parse-better-errors licensed under MIT. Repository: https://github.com/zkat/json-parse-better-errors
json-schema-traverse licensed under MIT. Repository: git+https://github.com/epoberezkin/json-schema-traverse.git
json-stringify-safe licensed under ISC. Repository: git://github.com/isaacs/json-stringify-safe
json3 licensed under MIT. Repository: git://github.com/bestiejs/json3.git
json5 licensed under MIT. Repository: git+https://github.com/json5/json5.git
jsonwebtoken licensed under MIT. Repository: https://github.com/auth0/node-jsonwebtoken
jsprim licensed under MIT. Repository: git://github.com/joyent/node-jsprim.git
jwa licensed under MIT. Repository: git://github.com/brianloveswords/node-jwa.git
jws licensed under MIT. Repository: git://github.com/brianloveswords/node-jws.git
killable licensed under ISC. Repository: https://github.com/marten-de-vries/killable.git
kind-of licensed under MIT. Repository: jonschlinkert/kind-of
kleur licensed under MIT. Repository: lukeed/kleur
lcid licensed under MIT. Repository: sindresorhus/lcid
leven licensed under MIT. Repository: sindresorhus/leven
levn licensed under MIT. Repository: git://github.com/gkz/levn.git
lie licensed under MIT. Repository: https://github.com/calvinmetcalf/lie.git
load-json-file licensed under MIT. Repository: sindresorhus/load-json-file
loader-runner licensed under MIT. Repository: git+https://github.com/webpack/loader-runner.git
loader-utils licensed under MIT. Repository: https://github.com/webpack/loader-utils.git
localforage licensed under Apache-2.0. Repository: git://github.com/localForage/localForage.git
locate-path licensed under MIT. Repository: sindresorhus/locate-path
lodash licensed under MIT. Repository: lodash/lodash
lodash.includes licensed under MIT. Repository: lodash/lodash
lodash.isboolean licensed under MIT. Repository: lodash/lodash
lodash.isinteger licensed under MIT. Repository: lodash/lodash
lodash.isnumber licensed under MIT. Repository: lodash/lodash
lodash.isplainobject licensed under MIT. Repository: lodash/lodash
lodash.isstring licensed under MIT. Repository: lodash/lodash
lodash.memoize licensed under MIT. Repository: lodash/lodash
lodash.merge licensed under MIT. Repository: lodash/lodash
lodash.omit licensed under MIT. Repository: lodash/lodash
lodash.once licensed under MIT. Repository: lodash/lodash
lodash.pick licensed under MIT. Repository: lodash/lodash
lodash.sortby licensed under MIT. Repository: lodash/lodash
log-symbols licensed under MIT. Repository: sindresorhus/log-symbols
loglevel licensed under MIT. Repository: git://github.com/pimterry/loglevel.git
loglevelnext licensed under MIT. Repository: shellscape/loglevelnext
lolex licensed under BSD-3-Clause. Repository: http://github.com/sinonjs/lolex.git
long-timeout licensed under MIT. Repository: git://github.com/tellnes/long-timeout.git
loose-envify licensed under MIT. Repository: git://github.com/zertosh/loose-envify.git
loud-rejection licensed under MIT. Repository: sindresorhus/loud-rejection
lowlight licensed under MIT. Repository: wooorm/lowlight
lru-cache licensed under ISC. Repository: git://github.com/isaacs/node-lru-cache.git
make-dir licensed under MIT. Repository: sindresorhus/make-dir
make-error licensed under ISC. Repository: git://github.com/JsCommunity/make-error.git
makeerror licensed under BSD-3-Clause. Repository: https://github.com/daaku/nodejs-makeerror
map-age-cleaner licensed under MIT. Repository: SamVerschueren/map-age-cleaner
map-cache licensed under MIT. Repository: jonschlinkert/map-cache
map-obj licensed under MIT. Repository: sindresorhus/map-obj
map-visit licensed under MIT. Repository: jonschlinkert/map-visit
md5.js licensed under MIT. Repository: https://github.com/crypto-browserify/md5.js.git
media-typer licensed under MIT. Repository: jshttp/media-typer
mem licensed under MIT. Repository: sindresorhus/mem
memory-fs licensed under MIT. Repository: https://github.com/webpack/memory-fs.git
memory-pager licensed under MIT. Repository: https://github.com/mafintosh/memory-pager.git
meow licensed under MIT. Repository: sindresorhus/meow
merge-descriptors licensed under MIT. Repository: component/merge-descriptors
merge-stream licensed under MIT. Repository: grncdr/merge-stream
methods licensed under MIT. Repository: jshttp/methods
micromatch licensed under MIT. Repository: micromatch/micromatch
miller-rabin licensed under MIT. Repository: git@github.com:indutny/miller-rabin
mime licensed under MIT. Repository: https://github.com/broofa/node-mime
mime-db licensed under MIT. Repository: jshttp/mime-db
mime-types licensed under MIT. Repository: jshttp/mime-types
mimic-fn licensed under MIT. Repository: sindresorhus/mimic-fn
mini-css-extract-plugin licensed under MIT. Repository: webpack-contrib/mini-css-extract-plugin
minimalistic-assert licensed under ISC. Repository: https://github.com/calvinmetcalf/minimalistic-assert.git
minimalistic-crypto-utils licensed under MIT. Repository: git+ssh://git@github.com/indutny/minimalistic-crypto-utils.git
minimatch licensed under ISC. Repository: git://github.com/isaacs/minimatch.git
minimist licensed under MIT. Repository: git://github.com/substack/minimist.git
mississippi licensed under BSD-2-Clause. Repository: git+https://github.com/maxogden/mississippi.git
mixin-deep licensed under MIT. Repository: jonschlinkert/mixin-deep
mkdirp licensed under MIT. Repository: https://github.com/substack/node-mkdirp.git
mobx licensed under MIT. Repository: https://github.com/mobxjs/mobx.git
mobx-react licensed under MIT. Repository: https://github.com/mobxjs/mobx-react.git
mobx-react-lite licensed under MIT. Repository: https://github.com/mobxjs/mobx-react-lite.git
moment licensed under MIT. Repository: https://github.com/moment/moment.git
mongodb licensed under Apache-2.0. Repository: git@github.com:mongodb/node-mongodb-native.git
move-concurrently licensed under ISC. Repository: git+https://github.com/npm/move-concurrently.git
ms licensed under MIT. Repository: zeit/ms
multicast-dns licensed under MIT. Repository: https://github.com/mafintosh/multicast-dns.git
multicast-dns-service-types licensed under MIT. Repository: https://github.com/mafintosh/multicast-dns-service-types.git
nan licensed under MIT. Repository: git://github.com/nodejs/nan.git
nanomatch licensed under MIT. Repository: micromatch/nanomatch
natural-compare licensed under MIT. Repository: git://github.com/litejs/natural-compare-lite.git
nedb licensed under SEE LICENSE IN LICENSE. Repository: git@github.com:louischatriot/nedb.git
negotiator licensed under MIT. Repository: jshttp/negotiator
neo-async licensed under MIT. Repository: git@github.com:suguru03/neo-async.git
next-tick licensed under MIT. Repository: git://github.com/medikoo/next-tick.git
nice-try licensed under MIT. Repository: https://github.com/electerious/nice-try.git
node-forge licensed under (BSD-3-Clause OR GPL-2.0). Repository: https://github.com/digitalbazaar/forge
node-gyp licensed under MIT. Repository: git://github.com/nodejs/node-gyp.git
node-int64 licensed under MIT. Repository: https://github.com/broofa/node-int64
node-libs-browser licensed under MIT. Repository: git+https://github.com/webpack/node-libs-browser.git
node-modules-regexp licensed under MIT. Repository: jamestalmage/node-modules-regexp
node-notifier licensed under MIT. Repository: git+ssh://git@github.com/mikaelbr/node-notifier.git
node-sass licensed under MIT. Repository: https://github.com/sass/node-sass
nopt licensed under ISC. Repository: https://github.com/npm/nopt.git
normalize-package-data licensed under BSD-2-Clause. Repository: git://github.com/npm/normalize-package-data.git
normalize-path licensed under MIT. Repository: jonschlinkert/normalize-path
normalize-url licensed under MIT. Repository: sindresorhus/normalize-url
npm-run-path licensed under MIT. Repository: sindresorhus/npm-run-path
npmlog licensed under ISC. Repository: https://github.com/npm/npmlog.git
number-is-nan licensed under MIT. Repository: sindresorhus/number-is-nan
nwsapi licensed under MIT. Repository: git://github.com/dperini/nwsapi.git
oauth-sign licensed under Apache-2.0. Repository: https://github.com/mikeal/oauth-sign
object-assign licensed under MIT. Repository: sindresorhus/object-assign
object-copy licensed under MIT. Repository: jonschlinkert/object-copy
object-inspect licensed under MIT. Repository: git://github.com/substack/object-inspect.git
object-is licensed under MIT. Repository: git://github.com/es-shims/object-is.git
object-keys licensed under MIT. Repository: git://github.com/ljharb/object-keys.git
object-visit licensed under MIT. Repository: jonschlinkert/object-visit
object.assign licensed under MIT. Repository: git://github.com/ljharb/object.assign.git
object.pick licensed under MIT. Repository: jonschlinkert/object.pick
obuf licensed under MIT. Repository: git@github.com:indutny/offset-buffer
on-finished licensed under MIT. Repository: jshttp/on-finished
on-headers licensed under MIT. Repository: jshttp/on-headers
once licensed under ISC. Repository: git://github.com/isaacs/once
onetime licensed under MIT. Repository: sindresorhus/onetime
opn licensed under MIT. Repository: sindresorhus/opn
optionator licensed under MIT. Repository: git://github.com/gkz/optionator.git
original licensed under MIT. Repository: https://github.com/unshiftio/original
os-browserify licensed under MIT. Repository: http://github.com/CoderPuppy/os-browserify.git
os-homedir licensed under MIT. Repository: sindresorhus/os-homedir
os-locale licensed under MIT. Repository: sindresorhus/os-locale
os-tmpdir licensed under MIT. Repository: sindresorhus/os-tmpdir
osenv licensed under ISC. Repository: https://github.com/npm/osenv
p-defer licensed under MIT. Repository: sindresorhus/p-defer
p-each-series licensed under MIT. Repository: sindresorhus/p-each-series
p-finally licensed under MIT. Repository: sindresorhus/p-finally
p-is-promise licensed under MIT. Repository: sindresorhus/p-is-promise
p-limit licensed under MIT. Repository: sindresorhus/p-limit
p-locate licensed under MIT. Repository: sindresorhus/p-locate
p-map licensed under MIT. Repository: sindresorhus/p-map
p-retry licensed under MIT. Repository: sindresorhus/p-retry
p-try licensed under MIT. Repository: sindresorhus/p-try
pako licensed under (MIT AND Zlib). Repository: nodeca/pako
parallel-transform licensed under MIT. Repository: git://github.com/mafintosh/parallel-transform
parse-asn1 licensed under ISC. Repository: git://github.com/crypto-browserify/parse-asn1.git
parse-entities licensed under MIT. Repository: wooorm/parse-entities
parse-json licensed under MIT. Repository: sindresorhus/parse-json
parse-passwd licensed under MIT. Repository: doowb/parse-passwd
parse5 licensed under MIT. Repository: git://github.com/inikulin/parse5.git
parseqs licensed under MIT. Repository: https://github.com/get/querystring.git
parseuri licensed under MIT. Repository: https://github.com/get/parseuri.git
parseurl licensed under MIT. Repository: pillarjs/parseurl
pascalcase licensed under MIT. Repository: jonschlinkert/pascalcase
passport-jwt licensed under MIT. Repository: https://github.com/themikenicholson/passport-jwt.git
path-browserify licensed under MIT. Repository: git://github.com/substack/path-browserify.git
path-dirname licensed under MIT. Repository: es128/path-dirname
path-exists licensed under MIT. Repository: sindresorhus/path-exists
path-is-absolute licensed under MIT. Repository: sindresorhus/path-is-absolute
path-is-inside licensed under (WTFPL OR MIT). Repository: domenic/path-is-inside
path-key licensed under MIT. Repository: sindresorhus/path-key
path-parse licensed under MIT. Repository: https://github.com/jbgutierrez/path-parse.git
path-to-regexp licensed under MIT. Repository: https://github.com/component/path-to-regexp.git
path-type licensed under MIT. Repository: sindresorhus/path-type
pbkdf2 licensed under MIT. Repository: https://github.com/crypto-browserify/pbkdf2.git
performance-now licensed under MIT. Repository: git://github.com/braveg1rl/performance-now.git
picomatch licensed under MIT. Repository: micromatch/picomatch
pify licensed under MIT. Repository: sindresorhus/pify
pinkie licensed under MIT. Repository: floatdrop/pinkie
pinkie-promise licensed under MIT. Repository: floatdrop/pinkie-promise
pirates licensed under MIT. Repository: https://github.com/ariporad/pirates.git
pkg-dir licensed under MIT. Repository: sindresorhus/pkg-dir
pn licensed under MIT. Repository: git://github.com/cscott/node-pn
portfinder licensed under MIT. Repository: git@github.com:indexzero/node-portfinder.git
posix-character-classes licensed under MIT. Repository: jonschlinkert/posix-character-classes
postcss licensed under MIT. Repository: postcss/postcss
postcss-modules-extract-imports licensed under ISC. Repository: https://github.com/css-modules/postcss-modules-extract-imports.git
postcss-modules-local-by-default licensed under MIT. Repository: https://github.com/css-modules/postcss-modules-local-by-default.git
postcss-modules-scope licensed under ISC. Repository: https://github.com/css-modules/postcss-modules-scope.git
postcss-modules-values licensed under ISC. Repository: git+https://github.com/css-modules/postcss-modules-values.git
postcss-selector-parser licensed under MIT. Repository: postcss/postcss-selector-parser
postcss-value-parser licensed under MIT. Repository: https://github.com/TrySound/postcss-value-parser.git
prepend-http licensed under MIT. Repository: sindresorhus/prepend-http
pretty-format licensed under MIT. Repository: https://github.com/facebook/jest.git
prismjs licensed under MIT. Repository: https://github.com/LeaVerou/prism.git
process licensed under MIT. Repository: git://github.com/shtylman/node-process.git
process-nextick-args licensed under MIT. Repository: https://github.com/calvinmetcalf/process-nextick-args.git
promise-inflight licensed under ISC. Repository: git+https://github.com/iarna/promise-inflight.git
prompts licensed under MIT. Repository: terkelg/prompts
prop-types licensed under MIT. Repository: facebook/prop-types
property-information licensed under MIT. Repository: wooorm/property-information
proxy-addr licensed under MIT. Repository: jshttp/proxy-addr
prr licensed under MIT. Repository: https://github.com/rvagg/prr.git
pseudomap licensed under ISC. Repository: git+https://github.com/isaacs/pseudomap.git
psl licensed under MIT. Repository: git@github.com:lupomontero/psl.git
public-encrypt licensed under MIT. Repository: https://github.com/crypto-browserify/publicEncrypt.git
pump licensed under MIT. Repository: git://github.com/mafintosh/pump.git
pumpify licensed under MIT. Repository: git://github.com/mafintosh/pumpify
punycode licensed under MIT. Repository: https://github.com/bestiejs/punycode.js.git
qs licensed under BSD-3-Clause. Repository: https://github.com/ljharb/qs.git
query-string licensed under MIT. Repository: sindresorhus/query-string
querystringify licensed under MIT. Repository: https://github.com/unshiftio/querystringify
radix-router licensed under MIT. Repository: https://github.com/charlieduong94/radix-router
randombytes licensed under MIT. Repository: git@github.com:crypto-browserify/randombytes.git
randomfill licensed under MIT. Repository: https://github.com/crypto-browserify/randomfill.git
range-parser licensed under MIT. Repository: jshttp/range-parser
raw-body licensed under MIT. Repository: stream-utils/raw-body
react licensed under MIT. Repository: https://github.com/facebook/react.git
react-dom licensed under MIT. Repository: https://github.com/facebook/react.git
react-fast-compare licensed under MIT. Repository: git+https://github.com/FormidableLabs/react-fast-compare.git
react-icons licensed under MIT. Repository: git+ssh://git@github.com:react-icons/react-icons.git
react-is licensed under MIT. Repository: https://github.com/facebook/react.git
react-syntax-highlighter licensed under MIT. Repository: git+https://github.com/conorhastings/react-syntax-highlighter.git
read-pkg licensed under MIT. Repository: sindresorhus/read-pkg
read-pkg-up licensed under MIT. Repository: sindresorhus/read-pkg-up
readable-stream licensed under MIT. Repository: git://github.com/nodejs/readable-stream
readdirp licensed under MIT. Repository: git://github.com/paulmillr/readdirp.git
realpath-native licensed under MIT. Repository: SimenB/realpath-native
redent licensed under MIT. Repository: sindresorhus/redent
refractor licensed under MIT. Repository: wooorm/refractor
regenerator-runtime licensed under MIT. Repository: https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime
regex-not licensed under MIT. Repository: jonschlinkert/regex-not
regexp.prototype.flags licensed under MIT. Repository: git://github.com/es-shims/RegExp.prototype.flags.git
remove-trailing-separator licensed under ISC. Repository: git+https://github.com/darsain/remove-trailing-separator.git
repeat-element licensed under MIT. Repository: jonschlinkert/repeat-element
repeat-string licensed under MIT. Repository: jonschlinkert/repeat-string
repeating licensed under MIT. Repository: sindresorhus/repeating
request licensed under Apache-2.0. Repository: https://github.com/request/request.git
request-promise-core licensed under ISC. Repository: git+https://github.com/request/promise-core.git
request-promise-native licensed under ISC. Repository: git+https://github.com/request/request-promise-native.git
require-directory licensed under MIT. Repository: git://github.com/troygoode/node-require-directory.git
require-main-filename licensed under ISC. Repository: git+ssh://git@github.com/yargs/require-main-filename.git
require_optional licensed under Apache-2.0. Repository: https://github.com/christkv/require_optional.git
requires-port licensed under MIT. Repository: https://github.com/unshiftio/requires-port
resolve licensed under MIT. Repository: git://github.com/browserify/resolve.git
resolve-cwd licensed under MIT. Repository: sindresorhus/resolve-cwd
resolve-dir licensed under MIT. Repository: jonschlinkert/resolve-dir
resolve-from licensed under MIT. Repository: sindresorhus/resolve-from
resolve-url licensed under MIT. Repository: lydell/resolve-url
ret licensed under MIT. Repository: git://github.com/fent/ret.js.git
retry licensed under MIT. Repository: git://github.com/tim-kos/node-retry.git
rimraf licensed under ISC. Repository: git://github.com/isaacs/rimraf.git
ripemd160 licensed under MIT. Repository: https://github.com/crypto-browserify/ripemd160
rsvp licensed under MIT. Repository: https://github.com/tildeio/rsvp.js.git
run-queue licensed under ISC. Repository: git+https://github.com/iarna/run-queue.git
safe-buffer licensed under MIT. Repository: git://github.com/feross/safe-buffer.git
safe-regex licensed under MIT. Repository: git://github.com/substack/safe-regex.git
safer-buffer licensed under MIT. Repository: git+https://github.com/ChALkeR/safer-buffer.git
sane licensed under MIT. Repository: https://github.com/amasad/sane
saslprep licensed under MIT. Repository: git+https://github.com/reklatsmasters/saslprep.git
sass-graph licensed under MIT. Repository: xzyfer/sass-graph
sass-loader licensed under MIT. Repository: webpack-contrib/sass-loader
saxes licensed under ISC. Repository: https://github.com/lddubeau/saxes.git
scheduler licensed under MIT. Repository: https://github.com/facebook/react.git
schema-utils licensed under MIT. Repository: https://github.com/webpack-contrib/schema-utils
scss-tokenizer licensed under MIT. Repository: https://github.com/sasstools/scss-tokenizer.git
select licensed under MIT. Repository: zenorocha/select
select-hose licensed under MIT. Repository: git+ssh://git@github.com/indutny/select-hose.git
selfsigned licensed under MIT. Repository: git://github.com/jfromaniello/selfsigned.git
semver licensed under ISC. Repository: https://github.com/npm/node-semver
send licensed under MIT. Repository: pillarjs/send
serialize-javascript licensed under BSD-3-Clause. Repository: git+https://github.com/yahoo/serialize-javascript.git
serve-index licensed under MIT. Repository: expressjs/serve-index
serve-static licensed under MIT. Repository: expressjs/serve-static
set-blocking licensed under ISC. Repository: git+https://github.com/yargs/set-blocking.git
set-value licensed under MIT. Repository: jonschlinkert/set-value
setimmediate licensed under MIT. Repository: YuzuJS/setImmediate
setprototypeof licensed under ISC. Repository: https://github.com/wesleytodd/setprototypeof.git
sha.js licensed under (MIT AND BSD-3-Clause). Repository: git://github.com/crypto-browserify/sha.js.git
shallow-clone licensed under MIT. Repository: jonschlinkert/shallow-clone
shebang-command licensed under MIT. Repository: kevva/shebang-command
shebang-regex licensed under MIT. Repository: sindresorhus/shebang-regex
shellwords licensed under MIT. Repository: git://github.com/jimmycuadra/shellwords.git
sift licensed under MIT. Repository: crcn/sift.js
signal-exit licensed under ISC. Repository: https://github.com/tapjs/signal-exit.git
sisteransi licensed under MIT. Repository: https://github.com/terkelg/sisteransi
slash licensed under MIT. Repository: sindresorhus/slash
snapdragon licensed under MIT. Repository: jonschlinkert/snapdragon
snapdragon-node licensed under MIT. Repository: jonschlinkert/snapdragon-node
snapdragon-util licensed under MIT. Repository: jonschlinkert/snapdragon-util
socket.io licensed under MIT. Repository: git://github.com/socketio/socket.io
socket.io-adapter licensed under MIT. Repository: git://github.com/socketio/socket.io-adapter.git
socket.io-client licensed under MIT. Repository: https://github.com/Automattic/socket.io-client.git
socket.io-parser licensed under MIT. Repository: https://github.com/Automattic/socket.io-parser.git
sockjs licensed under MIT. Repository: https://github.com/sockjs/sockjs-node.git
sockjs-client licensed under MIT. Repository: https://github.com/sockjs/sockjs-client.git
sort-keys licensed under MIT. Repository: sindresorhus/sort-keys
source-list-map licensed under MIT. Repository: https://github.com/webpack/source-list-map.git
source-map licensed under BSD-3-Clause. Repository: http://github.com/mozilla/source-map.git
source-map-loader licensed under MIT. Repository: https://github.com/webpack-contrib/source-map-loader.git
source-map-resolve licensed under MIT. Repository: lydell/source-map-resolve
source-map-support licensed under MIT. Repository: https://github.com/evanw/node-source-map-support
source-map-url licensed under MIT. Repository: lydell/source-map-url
space-separated-tokens licensed under MIT. Repository: wooorm/space-separated-tokens
sparse-bitfield licensed under MIT. Repository: https://github.com/mafintosh/sparse-bitfield.git
spdx-correct licensed under Apache-2.0. Repository: jslicense/spdx-correct.js
spdx-exceptions licensed under CC-BY-3.0. Repository: kemitchell/spdx-exceptions.json
spdx-expression-parse licensed under MIT. Repository: jslicense/spdx-expression-parse.js
spdx-license-ids licensed under CC0-1.0. Repository: shinnn/spdx-license-ids
spdy licensed under MIT. Repository: git://github.com/indutny/node-spdy.git
spdy-transport licensed under MIT. Repository: git://github.com/spdy-http2/spdy-transport.git
split-string licensed under MIT. Repository: jonschlinkert/split-string
sprintf-js licensed under BSD-3-Clause. Repository: https://github.com/alexei/sprintf.js.git
sshpk licensed under MIT. Repository: git+https://github.com/joyent/node-sshpk.git
ssri licensed under ISC. Repository: https://github.com/zkat/ssri
stack-utils licensed under MIT. Repository: tapjs/stack-utils
static-extend licensed under MIT. Repository: jonschlinkert/static-extend
statuses licensed under MIT. Repository: jshttp/statuses
stdout-stream licensed under MIT. Repository: mafintosh/stdout-stream
stealthy-require licensed under ISC. Repository: git+https://github.com/analog-nico/stealthy-require.git
stream-browserify licensed under MIT. Repository: git://github.com/browserify/stream-browserify.git
stream-each licensed under MIT. Repository: https://github.com/mafintosh/stream-each.git
stream-http licensed under MIT. Repository: git://github.com/jhiesey/stream-http.git
stream-shift licensed under MIT. Repository: https://github.com/mafintosh/stream-shift.git
strict-uri-encode licensed under MIT. Repository: kevva/strict-uri-encode
string-length licensed under MIT. Repository: sindresorhus/string-length
string-width licensed under MIT. Repository: sindresorhus/string-width
string.prototype.trimleft licensed under MIT. Repository: git://github.com/es-shims/String.prototype.trimLeft.git
string.prototype.trimright licensed under MIT. Repository: git://github.com/es-shims/String.prototype.trimRight.git
string_decoder licensed under MIT. Repository: git://github.com/nodejs/string_decoder.git
strip-ansi licensed under MIT. Repository: chalk/strip-ansi
strip-bom licensed under MIT. Repository: sindresorhus/strip-bom
strip-eof licensed under MIT. Repository: sindresorhus/strip-eof
strip-final-newline licensed under MIT. Repository: sindresorhus/strip-final-newline
strip-indent licensed under MIT. Repository: sindresorhus/strip-indent
style-loader licensed under MIT. Repository: webpack-contrib/style-loader
supports-color licensed under MIT. Repository: chalk/supports-color
supports-hyperlinks licensed under MIT. Repository: jamestalmage/supports-hyperlinks
symbol-tree licensed under MIT. Repository: https://github.com/jsdom/js-symbol-tree.git
tapable licensed under MIT. Repository: http://github.com/webpack/tapable.git
tar licensed under ISC. Repository: git://github.com/isaacs/node-tar.git
terminal-link licensed under MIT. Repository: sindresorhus/terminal-link
terser licensed under BSD-2-Clause. Repository: https://github.com/terser/terser
terser-webpack-plugin licensed under MIT. Repository: webpack-contrib/terser-webpack-plugin
test-exclude licensed under ISC. Repository: git+https://github.com/istanbuljs/test-exclude.git
throat licensed under MIT. Repository: https://github.com/ForbesLindesay/throat.git
through2 licensed under MIT. Repository: https://github.com/rvagg/through2.git
thunky licensed under MIT. Repository: git://github.com/mafintosh/thunky.git
timers-browserify licensed under MIT. Repository: git://github.com/jryans/timers-browserify.git
tiny-emitter licensed under MIT. Repository: https://github.com/scottcorgan/tiny-emitter.git
tmpl licensed under BSD-3-Clause. Repository: https://github.com/daaku/nodejs-tmpl
to-arraybuffer licensed under MIT. Repository: git://github.com/jhiesey/to-arraybuffer.git
to-fast-properties licensed under MIT. Repository: sindresorhus/to-fast-properties
to-object-path licensed under MIT. Repository: jonschlinkert/to-object-path
to-regex licensed under MIT. Repository: jonschlinkert/to-regex
to-regex-range licensed under MIT. Repository: micromatch/to-regex-range
toidentifier licensed under MIT. Repository: component/toidentifier
tough-cookie licensed under BSD-3-Clause. Repository: git://github.com/salesforce/tough-cookie.git
tr46 licensed under MIT. Repository: Sebmaster/tr46.js
trim-newlines licensed under MIT. Repository: sindresorhus/trim-newlines
true-case-path licensed under Apache-2.0. Repository: git+https://github.com/barsh/true-case-path.git
ts-jest licensed under MIT. Repository: git+https://github.com/kulshekhar/ts-jest.git
ts-node licensed under MIT. Repository: git://github.com/TypeStrong/ts-node.git
tslib licensed under Apache-2.0. Repository: https://github.com/Microsoft/tslib.git
tty-browserify licensed under MIT. Repository: git://github.com/substack/tty-browserify.git
tunnel-agent licensed under Apache-2.0. Repository: https://github.com/mikeal/tunnel-agent
tweetnacl licensed under Unlicense. Repository: https://github.com/dchest/tweetnacl-js.git
type licensed under ISC. Repository: medikoo/type
type-check licensed under MIT. Repository: git://github.com/gkz/type-check.git
type-detect licensed under MIT. Repository: git+ssh://git@github.com/chaijs/type-detect.git
type-fest licensed under (MIT OR CC0-1.0). Repository: sindresorhus/type-fest
type-is licensed under MIT. Repository: jshttp/type-is
typedarray licensed under MIT. Repository: git://github.com/substack/typedarray.git
typedarray-to-buffer licensed under MIT. Repository: git://github.com/feross/typedarray-to-buffer.git
typescript licensed under Apache-2.0. Repository: https://github.com/Microsoft/TypeScript.git
uglify-js licensed under BSD-2-Clause. Repository: mishoo/UglifyJS2
uglifyjs-webpack-plugin licensed under MIT. Repository: webpack-contrib/uglifyjs-webpack-plugin
union-value licensed under MIT. Repository: jonschlinkert/union-value
uniq licensed under MIT. Repository: git://github.com/mikolalysenko/uniq.git
unique-filename licensed under ISC. Repository: https://github.com/iarna/unique-filename.git
unique-slug licensed under ISC. Repository: git://github.com/iarna/unique-slug.git
unpipe licensed under MIT. Repository: stream-utils/unpipe
unset-value licensed under MIT. Repository: jonschlinkert/unset-value
upath licensed under MIT. Repository: git://github.com/anodynos/upath
uri-js licensed under BSD-2-Clause. Repository: http://github.com/garycourt/uri-js
urix licensed under MIT. Repository: lydell/urix
url licensed under MIT. Repository: https://github.com/defunctzombie/node-url.git
url-parse licensed under MIT. Repository: https://github.com/unshiftio/url-parse.git
use licensed under MIT. Repository: jonschlinkert/use
util licensed under MIT. Repository: git://github.com/defunctzombie/node-util
util-deprecate licensed under MIT. Repository: git://github.com/TooTallNate/util-deprecate.git
utils-merge licensed under MIT. Repository: git://github.com/jaredhanson/utils-merge.git
uuid licensed under MIT. Repository: https://github.com/uuidjs/uuid.git
v8-compile-cache licensed under MIT. Repository: https://github.com/zertosh/v8-compile-cache.git
v8-to-istanbul licensed under ISC. Repository: istanbuljs/v8-to-istanbul
validate-npm-package-license licensed under Apache-2.0. Repository: kemitchell/validate-npm-package-license.js
vary licensed under MIT. Repository: jshttp/vary
verror licensed under MIT. Repository: git://github.com/davepacheco/node-verror.git
victory licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-area licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-axis licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-bar licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-box-plot licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-brush-container licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-brush-line licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-candlestick licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-chart licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-core licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-create-container licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-cursor-container licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-errorbar licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-group licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-legend licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-line licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-pie licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-polar-axis licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-scatter licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-selection-container licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-shared-events licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-stack licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-tooltip licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-voronoi licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-voronoi-container licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
victory-zoom-container licensed under MIT. Repository: https://github.com/formidablelabs/victory.git
vm-browserify licensed under MIT. Repository: http://github.com/substack/vm-browserify.git
w3c-hr-time licensed under MIT. Repository: https://github.com/jsdom/w3c-hr-time
w3c-xmlserializer licensed under MIT. Repository: jsdom/w3c-xmlserializer
walker licensed under Apache-2.0. Repository: https://github.com/daaku/nodejs-walker
watchpack licensed under MIT. Repository: https://github.com/webpack/watchpack.git
wbuf licensed under MIT. Repository: git@github.com:indutny/wbuf
webidl-conversions licensed under BSD-2-Clause. Repository: jsdom/webidl-conversions
webpack licensed under MIT. Repository: https://github.com/webpack/webpack.git
webpack-cli licensed under MIT. Repository: https://github.com/webpack/webpack-cli.git
webpack-dev-middleware licensed under MIT. Repository: webpack/webpack-dev-middleware
webpack-dev-server licensed under MIT. Repository: https://github.com/webpack/webpack-dev-server.git
webpack-log licensed under MIT. Repository: https://github.com/webpack-contrib/webpack-log.git
webpack-sources licensed under MIT. Repository: git+https://github.com/webpack/webpack-sources.git
websocket-driver licensed under Apache-2.0. Repository: git://github.com/faye/websocket-driver-node.git
websocket-extensions licensed under MIT. Repository: git://github.com/faye/websocket-extensions-node.git
whatwg-encoding licensed under MIT. Repository: jsdom/whatwg-encoding
whatwg-mimetype licensed under MIT. Repository: jsdom/whatwg-mimetype
whatwg-url licensed under MIT. Repository: jsdom/whatwg-url
which licensed under ISC. Repository: git://github.com/isaacs/node-which.git
which-module licensed under ISC. Repository: git+https://github.com/nexdrew/which-module.git
wide-align licensed under ISC. Repository: https://github.com/iarna/wide-align
word-wrap licensed under MIT. Repository: jonschlinkert/word-wrap
worker-farm licensed under MIT. Repository: https://github.com/rvagg/node-worker-farm.git
wrap-ansi licensed under MIT. Repository: chalk/wrap-ansi
wrappy licensed under ISC. Repository: https://github.com/npm/wrappy
write-file-atomic licensed under ISC. Repository: git://github.com/npm/write-file-atomic.git
ws licensed under MIT. Repository: websockets/ws
xml-name-validator licensed under Apache-2.0. Repository: jsdom/xml-name-validator
xmlchars licensed under MIT. Repository: https://github.com/lddubeau/xmlchars.git
xtend licensed under MIT. Repository: git://github.com/Raynos/xtend.git
y18n licensed under ISC. Repository: git@github.com:yargs/y18n.git
yallist licensed under ISC. Repository: git+https://github.com/isaacs/yallist.git
yargs licensed under MIT. Repository: https://github.com/yargs/yargs.git
yargs-parser licensed under ISC. Repository: git@github.com:yargs/yargs-parser.git
yeast licensed under MIT. Repository: https://github.com/unshiftio/yeast.git
yn licensed under MIT. Repository: sindresorhus/yn`
licenseReport = licenseReport.replace(/\n/g, "<br />")
class PageLicenses extends React.Component<any, any> {
  public render() {
    return (
      <PageContainer {...this.props}>
        <BulmaHero
          className="is-light"
          title="Open source licenses"
          iconConfig={FaBalanceScale}
        >
        </BulmaHero>
        <div className="content" style={{marginRight: "1rem", marginLeft: "1rem"}} dangerouslySetInnerHTML={{ __html: licenseReport }} />
      </PageContainer>
    )
  }
}

export default PageLicenses
